resolve_composes: strip out profiles from modules
For Flatpaks, we want to allow specifying modules as name:stream/profile
to allow fine-tuning which packages from the module get installed into
the container - but when we switched Flatpaks to use resolve_composes
instead of having a separate plugin, the logic to strip out profiles
before triggering the build got lost.

Parsing the specs to remove the /profile causes us to reject a bare
'name' with a clear:

   atomic_reactor.plugin.PluginFailedException: plugin 'resolve_composes'
   raised an exception: ValueError: Module specification spam_modules should
   be in NAME:STREAM[:VERSION[:CONTEXT]][/PROFILE] format

exception - previously this would been passed to ODCS, which would fail
the compose. The tests are updated accordingly so all modules are in
name:stream format.

Signed-off-by: Owen W. Taylor <otaylor@fishsoup.net>