spec: BuildRequires python-docker-py
without it I see:
/usr/bin/python setup.py build
Traceback (most recent call last):
  File setup.py, line 13, in <module>
    from dock.constants import DESCRIPTION, HOMEPAGE
  File /builddir/build/BUILD/dock-1001c7ea0098f9afa9d44db61ddc3396d9e092e6/dock/__init__.py, line 14, in <module>
    from dock.api import *
  File /builddir/build/BUILD/dock-1001c7ea0098f9afa9d44db61ddc3396d9e092e6/dock/api.py, line 11, in <module>
    from dock.inner import DockerBuildWorkflow
  File /builddir/build/BUILD/dock-1001c7ea0098f9afa9d44db61ddc3396d9e092e6/dock/inner.py, line 16, in <module>
    from dock.build import InsideBuilder
  File /builddir/build/BUILD/dock-1001c7ea0098f9afa9d44db61ddc3396d9e092e6/dock/build.py, line 15, in <module>
    from dock.core import DockerTasker, LastLogger
  File /builddir/build/BUILD/dock-1001c7ea0098f9afa9d44db61ddc3396d9e092e6/dock/core.py, line 31, in <module>
    import docker
ImportError: No module named docker

I think it's because of setup.py now importing from dock.constants (970c63a622)