Freeze the setuptools version
Otherwise the CI for fedora unit test is failing, because
requests-gssapi cannot handle the newest setuptools. We can the
following eror

  × Running setup.py install for requests-gssapi did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-a4zlceds/requests-gssapi_3e65a70f952a4850a3147edf2f8c35db/setup.py", line 39, in <module>
          setup(
        File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 146, in setup
          _setup_distribution = dist = klass(attrs)
        File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 278, in __init__
          _Distribution.__init__(self, dist_attrs)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 286, in __init__
          self.finalize_options()
        File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 630, in finalize_options
          ep(self)
        File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 650, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 173, in load
          return functools.reduce(getattr, attrs, module)
      AttributeError: module 'setuptools.dist' has no attribute 'check_test_suite'
      [end of output]

Signed-off-by: mkosiarc <mkosiarc@redhat.com>